import { DiffResult, DiffLine, DiffKind, toHtmlSpans } from "@/lib/diff";

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

const formatLine = (line: DiffLine) => {
  if (line.type === "replace" && line.left && line.right) {
    return `~ ${line.left.value} → ${line.right.value}`;
  }

  if (line.left && !line.right) {
    return `- ${line.left.value}`;
  }

  if (line.right && !line.left) {
    return `+ ${line.right.value}`;
  }

  if (line.left && line.right) {
    return `  ${line.left.value}`;
  }

  return "";
};

export const diffToPlainText = (diff: DiffResult) =>
  diff.lines.map((line) => formatLine(line)).join("\n");

const CLASS_MAP: Record<DiffKind, string> = {
  equal: "diff-equal",
  insert: "diff-insert",
  delete: "diff-delete",
  replace: "diff-replace",
};

export const diffToHtml = (diff: DiffResult) => {
  const spans = toHtmlSpans(diff.inline);
  const body = spans
    .map(
      (span) =>
        `<span class="${CLASS_MAP[span.type]}" aria-label="${span.ariaLabel}">${escapeHtml(
          span.value,
        )}</span>`,
    )
    .join("");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Diffly Export</title>
    <style>
      :root {
        color-scheme: light dark;
        font-family: "JetBrains Mono", "SFMono-Regular", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
        line-height: 1.6;
      }
      body {
        margin: 2rem;
        background-color: #0f172a;
        color: #e2e8f0;
      }
      .diff-container {
        background: rgba(15, 23, 42, 0.85);
        border-radius: 0.75rem;
        padding: 1.5rem;
        border: 1px solid rgba(148, 163, 184, 0.2);
      }
      .diff-container span {
        border-radius: 0.35rem;
        padding: 0.1rem 0.2rem;
        white-space: pre-wrap;
      }
      .diff-equal {
        color: inherit;
      }
      .diff-insert {
        background: rgba(34, 197, 94, 0.2);
        color: #22c55e;
      }
      .diff-delete {
        background: rgba(239, 68, 68, 0.25);
        color: #f87171;
        text-decoration: line-through;
      }
      .diff-replace {
        background: rgba(249, 115, 22, 0.25);
        color: #fb923c;
      }
    </style>
  </head>
  <body>
    <article class="diff-container" aria-label="Diff export generated by Diffly">
      ${body}
    </article>
  </body>
</html>`;
};
